### ISSUE TITLE
Playing out with waffle to see if it helps team communication

### ISSUE THREAD

**Issue by clkao** [datproject/projects#10]

**Comment by clkao** [comment]
Here's the current view with a few repo included: https://waffle.io/datproject/projects

**Comment by almereyda** [comment]
I have bad feelings around using non-FLOSS software services within such a project: Shouldn't its infrastructure be self-hostable?

Thus https://huboard.com/ comes to mind, who also offer https://github.com/huboard/huboard .

If GitHub would be replaced by GitLab one day, there are also https://gitlab.com/laboard/laboard or the beautiful and simple http://kanban.leanlabs.io/ .

Also see https://twitter.com/almereyda/status/712694125901045760

cc/ @karissa

**Comment by okdistribute** [comment]
This is great, thanks @clkao ! I like how waffle surfaces these sub issues in the various poject repos

Thanks for the links @almereyda !
