### ISSUE TITLE
Roadmap visualisation

### ISSUE THREAD

**Issue by almereyda** [datproject/projects#11]
As this repository is dedicated to collect subprojects and their current state via GitHub issues, a simple visualisation may aid the comprehension of the overall state. 
### Who are the users?

External developers.
### How would the user interact with it?

Clicking a link.
### Why is the project important to the ecosystem?

Aggregating the status of the projects altogether in one view.
### What defines the minimum requirements to sufficiently release (version 1)

Fork https://github.com/gr2m/milestones and adapt.
### What are some stretch goals or interesting features for further releases (version 2, 3)

PR to support GitLab or multiple rows?

**Comment by okdistribute** [comment]
Thanks @almereyda ! I'm not sure I like how structured gr2m/milestones is.. I like the style of hubboard or waffle.io better, and we're still very independent.. im not sure we use milestones that much! But thanks for the suggestions
