### ISSUE TITLE
Prototype Fund Application

### ISSUE THREAD

**Issue by Kriesse** [datproject/projects#18]
Let’s see if we can come up with a small scoped project to apply with for this fund – seems like a perfect fit for Dat.
https://prototypefund.de/en/

> The Prototype fund supports the implementation of ideas in civic tech, data literacy, data security and software infrastructure. With a grant of up to €30,000, software developers, hackers and creatives can write code and develop open source prototypes over a period of six months.

People who pay tax in Germany are eligible to apply.

**Comment by joehand** [comment]
Seems like this round is over. Going to close this until we decide if we want to apply for the next round.
